// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class Agence
    {
        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string NomAgence { get; set; }
        [StringLength(50)]
        public string Adresse { get; set; }
        [StringLength(50)]
        public string codeAgence { get; set; }
        [StringLength(50)]
        public string Pays { get; set; }
        [StringLength(50)]
        public string Region { get; set; }
    }
}