// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class Client
    {
        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string Nom { get; set; }
        [StringLength(50)]
        public string Prenom { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateNaissance { get; set; }
        [StringLength(50)]
        public string LieuNaissance { get; set; }
        [StringLength(50)]
        public string NumeroIdentification { get; set; }
        public int Telephone { get; set; }
        [StringLength(50)]
        public string Adresse { get; set; }
        [StringLength(50)]
        public string Profession { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateInscription { get; set; }
    }
}