// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class roles
    {
        [Key]
        public int id_role { get; set; }
        [Required]
        [StringLength(45)]
        public string role { get; set; }
    }
}