// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class Scheme_StepSet
    {
        [Key]
        public long Id { get; set; }
        public long SchemeWorkFlowId { get; set; }
        public long StepWorkFlowId { get; set; }
        public int Numberstep { get; set; }
        public int Occurences { get; set; }
        [Required]
        [StringLength(50)]
        public string Activity { get; set; }

        [ForeignKey(nameof(SchemeWorkFlowId))]
        [InverseProperty(nameof(SchemeWorkFlowSet.Scheme_StepSet))]
        public virtual SchemeWorkFlowSet SchemeWorkFlow { get; set; }
        [ForeignKey(nameof(StepWorkFlowId))]
        [InverseProperty(nameof(StepWorkFlowSet.Scheme_StepSet))]
        public virtual StepWorkFlowSet StepWorkFlow { get; set; }
    }
}