// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class specialite
    {
        public specialite()
        {
            utilisateur = new HashSet<utilisateur>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(45)]
        public string nom_specialite { get; set; }

        [InverseProperty("id_specialiteNavigation")]
        public virtual ICollection<utilisateur> utilisateur { get; set; }
    }
}