// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class StepWorkFlowSet
    {
        public StepWorkFlowSet()
        {
            Scheme_StepSet = new HashSet<Scheme_StepSet>();
            TransitionSet = new HashSet<TransitionSet>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Controller { get; set; }
        [Required]
        [StringLength(50)]
        public string Action { get; set; }

        [InverseProperty("StepWorkFlow")]
        public virtual ICollection<Scheme_StepSet> Scheme_StepSet { get; set; }
        [InverseProperty("StepWorkFlow")]
        public virtual ICollection<TransitionSet> TransitionSet { get; set; }
    }
}