// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class structure_interne
    {
        public structure_interne()
        {
            utilisateur = new HashSet<utilisateur>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(255)]
        public string email { get; set; }
        [Required]
        [StringLength(45)]
        public string nom_structure { get; set; }
        [StringLength(255)]
        public string telephone { get; set; }

        [InverseProperty("structure_interneNavigation")]
        public virtual ICollection<utilisateur> utilisateur { get; set; }
    }
}