// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class ticket
    {
        [Key]
        public int id { get; set; }
        public DateTime? datecreation { get; set; }
        [StringLength(45)]
        public string description { get; set; }
        [StringLength(45)]
        public string numticket { get; set; }
        public long? id_secretaire { get; set; }
    }
}