// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class TransitionSet
    {
        [Key]
        [StringLength(128)]
        public string Id { get; set; }
        [Required]
        [StringLength(50)]
        public string TransitionName { get; set; }
        [Required]
        [StringLength(50)]
        public string ActivityFrom { get; set; }
        [Required]
        [StringLength(50)]
        public string ActivityTo { get; set; }
        [Required]
        [StringLength(50)]
        public string ConditionName { get; set; }
        public long StepWorkFlowId { get; set; }

        [ForeignKey(nameof(StepWorkFlowId))]
        [InverseProperty(nameof(StepWorkFlowSet.TransitionSet))]
        public virtual StepWorkFlowSet StepWorkFlow { get; set; }
    }
}