// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkFlowDynamic.DataEntityTypes
{
    public partial class utilisateur
    {
        [Required]
        [StringLength(3)]
        public string profil { get; set; }
        [Key]
        public long id_utilisateur { get; set; }
        public bool? active { get; set; }
        [Required]
        [StringLength(45)]
        public string adresse { get; set; }
        public DateTime? datenaiss { get; set; }
        [Required]
        [StringLength(45)]
        public string email { get; set; }
        [StringLength(45)]
        public string login { get; set; }
        [Required]
        [StringLength(45)]
        public string nom { get; set; }
        [StringLength(45)]
        public string passwordd { get; set; }
        [Required]
        [StringLength(45)]
        public string prenom { get; set; }
        [StringLength(45)]
        public string sexe { get; set; }
        [Required]
        [StringLength(255)]
        public string telephone { get; set; }
        [StringLength(45)]
        public string specialite { get; set; }
        [StringLength(45)]
        public string fonction { get; set; }
        public int? structure_interne { get; set; }
        public int? id_specialite { get; set; }

        [ForeignKey(nameof(id_specialite))]
        [InverseProperty("utilisateur")]
        public virtual specialite id_specialiteNavigation { get; set; }
        [ForeignKey(nameof(structure_interne))]
        [InverseProperty("utilisateur")]
        public virtual structure_interne structure_interneNavigation { get; set; }
    }
}